# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/783850d4-b511-46e4-a690-11aceed00e7d";
    fsType = "btrfs";
    options = [ "subvol=nixosroot" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/783850d4-b511-46e4-a690-11aceed00e7d";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/783850d4-b511-46e4-a690-11aceed00e7d";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/61D4-F619";
    fsType = "vfat";
    options = [
      "rw"
      "utf8"
    ];
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
