--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jasperro/.config/wpg/wallpapers/pauloflop_0.jpg"

-- Special
background="#090B05"
foreground="#dcdad2"
cursor="#dcdad2"

-- Colors
color0="#090B05"
color1="#CC5E46"
color2="#7C8474"
color3="#958A74"
color4="#E08872"
color5="#ABA798"
color6="#C7B6A7"
color7="#dcdad2"
color8="#9a9893"
color9="#CC5E46"
color10="#7C8474"
color11="#958A74"
color12="#E08872"
color13="#ABA798"
color14="#C7B6A7"
color15="#dcdad2"
