# Shell variables
# Generated by 'wal'
wallpaper='/home/jasperro/.config/wpg/wallpapers/mikereyfman_6.jpg'

# Special
background='#111513'
foreground='#dbdde3'
cursor='#dbdde3'

# Colors
color0='#111513'
color1='#6D8AA0'
color2='#5D9CC9'
color3='#96A0A8'
color4='#B7C5BA'
color5='#AEB7C7'
color6='#BBC4D1'
color7='#dbdde3'
color8='#999a9e'
color9='#6D8AA0'
color10='#5D9CC9'
color11='#96A0A8'
color12='#B7C5BA'
color13='#AEB7C7'
color14='#BBC4D1'
color15='#dbdde3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
