# Shell variables
# Generated by 'wal'
wallpaper='/home/jasperro/.config/wpg/wallpapers/pauloflop_0.jpg'

# Special
background='#090B05'
foreground='#dcdad2'
cursor='#dcdad2'

# Colors
color0='#090B05'
color1='#CC5E46'
color2='#7C8474'
color3='#958A74'
color4='#E08872'
color5='#ABA798'
color6='#C7B6A7'
color7='#dcdad2'
color8='#9a9893'
color9='#CC5E46'
color10='#7C8474'
color11='#958A74'
color12='#E08872'
color13='#ABA798'
color14='#C7B6A7'
color15='#dcdad2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
