--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jasperro/.config/wpg/wallpapers/mikereyfman_6.jpg"

-- Special
background="#111513"
foreground="#dbdde3"
cursor="#dbdde3"

-- Colors
color0="#111513"
color1="#6D8AA0"
color2="#5D9CC9"
color3="#96A0A8"
color4="#B7C5BA"
color5="#AEB7C7"
color6="#BBC4D1"
color7="#dbdde3"
color8="#999a9e"
color9="#6D8AA0"
color10="#5D9CC9"
color11="#96A0A8"
color12="#B7C5BA"
color13="#AEB7C7"
color14="#BBC4D1"
color15="#dbdde3"
