# Shell variables
# Generated by 'wal'
wallpaper='/home/jasperro/.config/wpg/wallpapers/markbridger_2.jpg'

# Special
background='#120c08'
foreground='#d7c89f'
cursor='#d7c89f'

# Colors
color0='#120c08'
color1='#635352'
color2='#9D4827'
color3='#97592F'
color4='#9D6C54'
color5='#7C852C'
color6='#AD9753'
color7='#d7c89f'
color8='#968c6f'
color9='#635352'
color10='#9D4827'
color11='#97592F'
color12='#9D6C54'
color13='#7C852C'
color14='#AD9753'
color15='#d7c89f'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
