--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jasperro/.config/wpg/wallpapers/markbridger_2.jpg"

-- Special
background="#120c08"
foreground="#d7c89f"
cursor="#d7c89f"

-- Colors
color0="#120c08"
color1="#635352"
color2="#9D4827"
color3="#97592F"
color4="#9D6C54"
color5="#7C852C"
color6="#AD9753"
color7="#d7c89f"
color8="#968c6f"
color9="#635352"
color10="#9D4827"
color11="#97592F"
color12="#9D6C54"
color13="#7C852C"
color14="#AD9753"
color15="#d7c89f"
