# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/5fb1e482-5f6a-42b1-8bcc-83bf49fb025f";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/5fb1e482-5f6a-42b1-8bcc-83bf49fb025f";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/5fb1e482-5f6a-42b1-8bcc-83bf49fb025f";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/5fb1e482-5f6a-42b1-8bcc-83bf49fb025f";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/BEE7-ACDF";
      fsType = "vfat";
    };

  fileSystems."/.snapshots" =
    {
      device = "/dev/disk/by-uuid/5fb1e482-5f6a-42b1-8bcc-83bf49fb025f";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
