# Shell variables
# Generated by 'wal'
wallpaper='/home/jasperro/.config/wpg/wallpapers/Road.jpg'

# Special
background='#18120f'
foreground='#bab5ba'
cursor='#bab5ba'

# Colors
color0='#18120f'
color1='#90643B'
color2='#9D704D'
color3='#B68656'
color4='#CE9760'
color5='#206490'
color6='#5C718A'
color7='#bab5ba'
color8='#827e82'
color9='#90643B'
color10='#9D704D'
color11='#B68656'
color12='#CE9760'
color13='#206490'
color14='#5C718A'
color15='#bab5ba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
