# Shell variables
# Generated by 'wal'
wallpaper='tekapo-new-zealand-trey-ratcliff-2-X2.jpg'

# Special
background='#0c1815'
foreground='#c3d1de'
cursor='#c3d1de'

# Colors
color0='#0c1815'
color1='#587190'
color2='#827D82'
color3='#628FAE'
color4='#45A6C4'
color5='#62AFCC'
color6='#9F9BAB'
color7='#c3d1de'
color8='#88929b'
color9='#587190'
color10='#827D82'
color11='#628FAE'
color12='#45A6C4'
color13='#62AFCC'
color14='#9F9BAB'
color15='#c3d1de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
