# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # fileSystems."/" = {
  #   device = "/dev/mapper/crypted";
  #   fsType = "btrfs";
  #   options = [ "subvol=@nixosroot" ];
  # };

  # boot.initrd.luks.devices."crypted".device =
  #   "/dev/disk/by-uuid/6241c212-ec7c-464c-b5bf-4971e8cd1987";

  # fileSystems."/nix" = {
  #   device = "/dev/mapper/crypted";
  #   fsType = "btrfs";
  #   options = [ "subvol=@nix" ];
  # };

  # fileSystems."/home" = {
  #   device = "/dev/mapper/crypted";
  #   fsType = "btrfs";
  #   options = [ "subvol=@home" ];
  # };

  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/90D4-E485";
  #   fsType = "vfat";
  #   options = [
  #     "fmask=0022"
  #     "dmask=0022"
  #   ];
  # };

  # swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
