# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/9ea1a5d3-96b2-4a49-909f-4a567483a761";
      fsType = "btrfs";
      options = [ "subvol=@nixosroot" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/9ea1a5d3-96b2-4a49-909f-4a567483a761";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/9ea1a5d3-96b2-4a49-909f-4a567483a761";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/9ea1a5d3-96b2-4a49-909f-4a567483a761";
      fsType = "btrfs";
      options = [ "subvol=@nixosvar" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/D5A0-759F";
      fsType = "vfat";
    };

  fileSystems."/.snapshots" =
    {
      device = "/dev/disk/by-uuid/9ea1a5d3-96b2-4a49-909f-4a567483a761";
      fsType = "btrfs";
      options = [ "subvol=/.snapshots" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
