name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - update_flake_lock_action

jobs:
  nixos_dry_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - doosje
          - superlaptop
          - koekie
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Dry build nixos configurations
        run: nix build --dry-run .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
