name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  nixos_dry_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Dry build nixos configuration (doosje)
        run: nix build --dry-run .#nixosConfigurations.doosje.config.system.build.toplevel
